### ISSUE TITLE
Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by uuangian** [celsomiranda/hexo-renderer-markdown-it#8]
After init new hexo , uninstall renderer-md and installed this reander in win7, when i run hexo g, 

there are some errors. I am not sure there is something wrong whith bluebird

TypeError: Cannot read property 'render' of undefined
    at Hexo.module.exports (e:\myweb\t3\node_modules\hexo-renderer-markdown-it\lib\renderer.js:14:46)
    at Hexo.tryCatcher (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\util.js:24:31)
    at Hexo.<anonymous> (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\method.js:15:34)
    at e:\myweb\t3\node_modules\hexo\lib\hexo\render.js:51:21
    at tryCatcher (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromiseAtPostResolution (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\promise.js:224:10)
    at Async._drainQueue (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\async.js:180:12)
    at Async._drainQueues (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\async.js:185:10)
    at Immediate.Async.drainQueues [as _onImmediate] (e:\myweb\t3\node_modules\hexo\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

The environment is:
hexo: 3.0.0
os: win7 32bit

**Comment by celsomiranda** [comment]
What's your node version?

I don't have windows7 installed but I can't reproduce this in win8.1

**Comment by celsomiranda** [comment]
Oh I got it.
This happens because you haven't set any options in the `_config.yml` file.

Will correct this

**Comment by uuangian** [comment]
worked fine.

**Comment by celsomiranda** [comment]
Thanks. 

Now, if no options are specified it will assume you chose `´default´`.
